let products = [{
        name: "Sunflower-Refined-Oil-Sun-Lite",
        tag: "Sunflower-Refined-Oil-Sun-Lite",
        des: "this is discription",
        price: 594,
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Saffola Gold Refined Cooking oil | Blend of Rice Bran & Sunflower oil | Helps Keeps Heart Healthy | 1 Litre pouch",
        tag: "Saffola-Gold",
        des: " Saffola Gold, Dual Seed Technology with goodness of 2 oils in 1, rice bran oil and sunflower oil, ensures a good balance of MUFA, PUFA for better heart health in comparison to single seed oils ",
        price: 219,
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Dhara Kachhi Ghani Mustard Oil Pouch, 1L",
        tag: "Dhara-Kachhi-Ghani",
        price: 177,
        des: " material_features: vegetarian, Light and healthy that is easy to digest",
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Cadbury Oreo Original Chocolatey Sandwich (Vanilla Creme) Biscuit Family Pack, 300g",
        tag: "Cadbury-Oreo",
        des: " This rich vanilla creme filling cookies contain 483 calories and 19.6g of fat and 0mg of cholesterol per 100g",
        price: 64,
        catagory: "biscuit",
        inCart: 0,
    },

    {
        name: "Saffola Gold Refined Cooking oil | Blend of Rice Bran & Sunflower oil | Helps Keeps Heart Healthy | 5 Litre jar",
        tag: "Saffola-Gold-Refined",
        des: "Saffola Gold Dual Seed Technology with goodness of 2 oils in 1, rice bran oil and sunflower oil, ensures a good balance of MUFA, PUFA for better heart health in comparison to single seed oils",
        catagory: "oil",
        price: 1170,
        inCart: 0,
    },
    {
        name: "Saffola Total Refined Cooking oil | Blend of Rice Bran & Safflower oil | Helps Manage Cholesterol | 5 Litre jar",
        tag: "Saffola-Total",
        des: "Saffola Total Dual Seed Technology with goodness of 2 oils in 1, rice bran oil and safflower oil, ensures a good balance of MUFA, PUFA for better nutrition through fats, compared to single seed oils",
        catagory: "oil",
        price: 1261,
        inCart: 0,
    },
    {
        name: "Fortune Premium Kachi Ghani Pure Mustard Oil, 1tr PET Bottle",
        tag: "fanta",
        des: " this is discription",
        price: 70,
        catagory: "food",
        inCart: 0,
    },
    {
        name: "Fortune Premium Kachi Ghani Pure Mustard Oil, 1tr PET Bottle",
        tag: "Fortune-Premium",
        des: "Made from Cold Pressed (Kachi Ghani) Technology using Finest Mustard Seeds - Rich in Omega 3 & 6 that boost Immunity",
        price: 181,
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Emami Healthy and Tasty Physically Refined Rice Bran Oil Pouch, 1L",
        tag: "Emami-Healthy-and-Tasty",
        des: "material_features: vegetarian Tocols are antioxidants present in rice bran oil that helps in removing damaging free radicals from the body",
        price: 210,
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Mahakosh Soyabean Oil, Refined 1L Pouch",
        tag: "Mahakosh-Soyabean-Oil",
        des: "Contains Polyunsaturated Fatty Acids (PUFA) which maintains heart health",
        price: 171,
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Phalada Pure & Sure Pure & Sure Organic Sunflower Oil | Sunflower Oil for Cooking | High in Antioxidants, Delicious & Healthy Sunflower Cooking Oil (1 Litre)",
        tag: "halada-Pure-&-Sure-Pure-&-Sure-Organic-Sunflower-Oil",
        des: " this is discription",
        price: 340,
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Delmonte Extra Light Olive Oil PET, 2L",
        tag: "Delmonte-Extra-Light-Olive-Oil",
        des: "Brought to you from the house of Del Monte imported especially from Italy and Spain",
        price: 936,
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Patanjali Mustard Oil, 1 Litre",
        tag: "Patanjali-Mustard-Oil",
        price: 205,
        des: "Mustard oil, because of its anti-microbial properties, it is used as a preservative for pickles",
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Parachute jumbo pack 100% pure coconut oil 600 ml (bottle )",
        tag: "Parachute-jumbo-pack",
        des: "Nothing but 100% pure coconut oil Is made with the finest hand-picked Coconuts Contains no added preservatives or chemicals Fresh nutty fragrance of pure coconut oil Long lasting freshness 27 quality tests and 5 stage purification process – for 100% purity every time",
        catagory: "oil",
        price: 198,
        inCart: 0,
    },
    {
        name: "Figaro Olive Oil- Pure Olive Oil- Ideal for Indian Dishes-Imported from Spain- 500ml Tin",
        tag: "Figaro-Olive-Oil",
        des: "Figaro Olive Oil is an excellent all purpose edible oil loaded with goodness of pure olives. Organic : Yes It has mutiple health benefits- rich source of Vitamin E, full of anti-oxidants, mantains cardio-circulatory system, regulate cholesterol level It is suitable for all types of cooking - sauteing- vegetable Saute; stir fry-vegetable stir fry ; shallow frying- bhindi fry, omlette Imported from Spain It is free from Argemone Oil",
        price: 516,
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "phalada pure & sure Castor Oil, 500ml",
        tag: "phalada-pure-&-sure-Castor-Oil",
        des: " 100 percent certified organic castor oil, made from the finest quality castor seeds sourced from certified organic farms across India, 100 percent cold pressed oil",
        price: 200,
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Dabur Amla Hair Oil - for Strong, Long and Thick hair - 550 ml",
        tag: "Dabur-Amla-Hair-Oil",
        des: " Dabur Amla hair oil has amla extracts. Amla is known to be a power fruit for your hair. As the power of amla nourishes your scalp from within, your hair is strengthened from root to tip",
        price: 206,
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Kesh King Ayurvedic Anti Hairfall Hair Oil, 300ml",
        tag: "Kesh-King",
        des: " Contains the goodness of 21 Ayurvedic herbs like Bhringraja, Amalaki, Methi, Brahmi, Japa, Lodhra, Manjistha, Jatamansi",
        price: 247,
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Bio - Oil Original Face & Body Oil, suitable for Acne Scar Removal, Pigmentation, Dark Spots & Stretch Marks & Ageing Signs for Glowing Skin with Vitamin A & E; All Skin Types | 200ml",
        tag: "Bio-Oil",
        des: "One product for multiple skin issues.Bio - Oil - Moisturiser for Face and Body. Dermatologically Tested and Clinically Proven. Won 419* Awards.#1 Mutliuse skin care oil in 25 countries PACKED WITH POWERFUL blend of OILS - Vitamin A Oil promotes the formation of new collagen and assists in skin renewal, increasing skin elasticity. Vitamin E Oil, Chamomile Oil, Sunflower Oil, and Lavender Oil are anti-inflammatory and promote healthy skin Bio - Oil improves appearance of Dark Spots, Acne Scars and Pigmentation.",
        price: 600,
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Biotique Bio Bhringraj Therapeutic Hair Oil for Falling Hair Intensive Hair Regrowth Treatment, 120ml",
        tag: "Biotique-Bio",
        des: " Alcohol free, not tested on animals, natural ingredients, paraben free; How to use: Apply liberally to dry hair and scalp. Massage in gently with circular motions. Leave on for half an hour. Rinse well with water.",
        price: 95,
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Navratna Ayurvedic cool hair oil with 9 herbal ingredients, 500ml",
        tag: "Navratna-Ayurvedic",
        des: " An ayurvedic oil made from a unique blend of nine ayurvedic herbs delivers superlatively desired benefits of relaxation and rejuvenation. For Men & Women",
        price: 265,
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "WishCare® Premium Cold Pressed Castor Oil - Pure & Virgin Grade - For Healthy Hair and Skin - 200 Ml",
        tag: "WishCare-Premium",
        price: 145,
        des: " PREMIUM QUALITY - 100% NATURAL & PURE : Produced with the highest quality standards using real castor seed, sourced directly from artisanal farmers in India. Our Cold Pressed Castor Oil is produced from Hexane-Free Extraction which gives it Dark Golden Color. Only The Best Castor Seeds from Kerala,India Are Picked And Extracted By Cold Press To Preserve The Botanical Actives To Retain Highest Quality Grade. Our FlipTop Cap, Comb Applicator and bottle design makes the oil easy to use",
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Ustraa Beard Growth Oil - 35ml - More Beard Growth, With Redensyl, 8 Natural Oils including Jojoba Oil, Vitamin E, Nourishment & Strengthening, No Sulphates, No Parabens, No Silicone, No Mineral Oil",
        tag: "Ustraa-Beard-Growth",
        price: 299,
        des: " Beard Growth test conducted in an independent lab shows upto 40% more hair growing cells with the USTRAA Beard Growth Oil.",
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Baidyanath Mahabhringraj Tel (Original) | Hairfall Control | Ayurvedic Medicated Hair Oil | 4X More Effective | For All Hair Types (Male & Female) - 200ml",
        tag: "Baidyanath-Mahabhringraj",
        des: " HELPS IN HAIR FALL CONTROL: Mahabhringraj Oil nourishes hair follicles and is helpful in maintaining stronger hair roots thereby preventing hair fall. It deeply nourishes the scalp resulting in healthy, strong, and lustrous hair.",
        catagory: "oil",
        price: 217,
        inCart: 0,
    },
    {
        name: "WOW Skin Science Onion Black Seed Hair Oil - WITH COMB APPLICATOR - Controls Hair Fall - NO Mineral Oil, Silicones, Cooking Oil & Synthetic Fragrance - 100mL",
        tag: "WOW-Skin-Science",
        des: " Get strong and lustrous hair with WOW Skin Science onion black seed hair oil with comb applicator. The built-in comb applicator helps detangle hair and spread the oil evenly onto each strand",
        price: 279,
        catagory: "oil",
        inCart: 0,
    },
    {
        name: "Alpino Natural Peanut Butter Crunch 1 KG | Unsweetened | 100% Roasted Peanuts | No Added Sugar, Salt, or Hydrogenated Oils | High Protein Peanut Butter Crunchy | Gluten-Free | Vegan",
        tag: "Alpino-Natural-Peanut-Butter",
        des: " Unsweetened | Made With 100% Roasted Peanuts | No Added Sugar | No Added Salt | No Hydrogenated Oils | 100% Non-GMO | Gluten-Free | Vegan",
        price: 374,
        catagory: "nut-butters",
        inCart: 0,
    },
    {
        name: "Yogabar Crunchy Peanut Butter Unsweetened | Premium Non GMO Slow Roasted Peanut Butter| No Added Sugar Peanut Butter Crunchy | No Palm Oil & Vegan 400g",
        tag: "Yogabar-Crunchy-Peanut-Butter",
        des: " Made of 100% non-GMO peanuts Yoga bar peanut butter | Slow-roasted, slow ground in small batches for superior flavour 25% Protein per serving | High in fibre | Zero Trans fat | Zero Cholesterol Highly Nutritious | Dairy Free | Vegan | Keto Friendly 100% Natural and no preservatives",
        price: 209,
        catagory: "nut-butters",
        inCart: 0,
    },
    {
        name: "Nutella Hazelnut Spread with Cocoa, 750g",
        tag: "Nutella-Hazelnut",
        des: " A unique and unbeatable taste Contains no artificial colours Country of Origin: Poland Contains no artificial preservatives Spread on your Bread for Breakfast to start Positively your day It's so delicious that a little goes a long way",
        price: 680,
        catagory: "nut-butters",
        inCart: 0,
    },
    {
        name: "Dabur Honey :100% Pure World's No.1 Honey Brand with No Sugar Adulteration - 1kg (Get 20% Extra)",
        tag: "Dabur-Honey",
        des: " One tablespoon of Dabur honey with warm water daily morning will help you in managing weight and reducing one size in 90days (clinically tested)",
        price: 387,
        catagory: "honey",
        inCart: 0,
    },
    {
        name: "Saffola Honey, 100% Pure NMR tested Honey, 1.0kg",
        tag: "Saffola-Honey",
        des: " Saffola Honey is exactly like how Honey should be – 100% Pure and Natural No Added Sugar Saffola Honey contains natural antioxidants which help build immunity Saffola Honey is tested using the latest NMR technology to ensure it is free from any adulteration Saffola Honey is a rich source of nutrition for you and your family Serves as a natural sweetner in tea, coffee and breakfast cereals",
        price: 390,
        catagory: "honey",
        inCart: 0,
    },
    {
        name: "Veeba Mayonnaise Combo - Eggless Mayonnaise, 250gm with Garlic Mayonnaise, 250gm and Burger Mayonnaise 250gm - Pack of 3",
        tag: "Veeba-Mayonnaise",
        price: 243,
        des: " Created especially for the Indian palate, these 3 light and creamy Eggless Mayonnaise from Veeba are a must in every sandwich, wrap and burger.",
        catagory: "mayonnaise",
        inCart: 0,
    },
    {
        name: "NAAGIN Indian Spice Essentials - Crispy Chilli Oil | Made with real Guntur Chillies| Mildly Spicy - 2/10 heat level | Vegan | Dip, Cook, Marinate| No artificial colours, flavor, additives or preservatives | Perfect for stir-fries, noodles, pizzas and salad (140g)",
        tag: "NAAGIN-Indian-Spice",
        des: " INDIAN SPICE ESSENTIALS : CRISPY CHILLI OIL: NAAGIN Crispy Chilli Oil brings out the best of almost any pairing you can think of. Our newest kitchen shelf and dining table must-have is built on a base of global-favourite Guntur chillies, slow-roasted to perfection and a special blend of crispy-crunchy bits, along with a solid dose of umami you can savour. While most chilli oils are just infused, we bring you a crispy classic which is 100% vegan, has no added sugars and no transfat.",
        catagory: "spices&masalas",
        price: 388,
        inCart: 0,
    },
    {
        name: "Tata Sampann Turmeric Powder Masala with Natural Oils, 200g",
        tag: "Tata-Sampann-Turmeric",
        des: " Highly Aromatic Turmeric: Enjoy the rich taste of Tata Sampann Turmeric Powder in all your favourite dishes",
        price: 55,
        catagory: "spices&masalas",
        inCart: 0,
    },
    {
        name: "Tata Sampann Coriander Powder Masala with Natural Oils, 200g",
        tag: "Tata-Sampann-Coriander",
        des: " Masaledar Sach: Coriander gets its properties and taste from its naturally occurring volatile oils Contain Natural Oils*: Made from whole spices which contain natural oils Rich Quality Coriander: Enjoy the rich taste of Tata Sampann Coriander Powder in all your favourite dishes",
        price: 71,
        catagory: "spices&masalas",
        inCart: 0,
    },
    {
        name: "Tata Sampann Kitchen King Masala with Natural Oils, 100g",
        tag: "Tata-Sampann-Kitchen-King-Masala",
        des: " Highly Aromatic: Make every bite aromatic and full of flavour with the rich taste of Tata Sampann Kitchen King Masala",
        price: 63,
        catagory: "spices&masalas",
        inCart: 0,
    },
    {
        name: "Tata Sampann Punjabi Chole Masala with Natural Oils, 100g",
        tag: "Tata-Sampann-Punjabi-Chole-Masala",
        des: " Highly Aromatic: Make every bite aromatic and full of flavour with the rich taste of Tata Sampann Punjabi Chole Masala With Natural Oils: Made from whole spices that retain their natural oils",
        price: 59,
        catagory: "spices&masalas",
        inCart: 0,
    },
    {
        name: "Tata Sampann Chilli Powder Masala with Natural Oils, 500g",
        tag: "Tata-Sampann-Chilli-Powder-Masala",
        des: " Contain Natural Oils*: Made from whole spices which contain natural oils Sourced from Guntur: The chilli powder is sourced from Guntur region in Andhra Pradesh, which is famous for its chillies",
        price: 230,
        catagory: "spices&masalas",
        inCart: 0,
    },
    {
        name: "Tata Sampann Chaat Masala with Natural Oils, 100g",
        tag: "Tata-Sampann-Chaat-Masala",
        des: " All our blended spices have been specially crafted by Indian master chef Sanjeev kapoor We have combined whole spices that have their natural oils retained to ensure that you get consistent, top quality flavours on your table Goodness intact Consistency quality",
        price: 62,
        catagory: "spices&masalas",
        inCart: 0,
    },
    {
        name: "Tata Sampann Low Oil Absorb Pakoda Mix, Instant Ready to Cook Mix, 180g",
        tag: "Tata-Sampann-Low-Oil-Absorb-Pakoda",
        price: 70,
        des: " READY TO COOK MIX: Enjoy instant snack with Tata Sampann Pakoda mix that can be made in 15 minutes",
        catagory: "spices&masalas",
        inCart: 0,
    },
    {
        name: "Tata Salt, Vacuum Evaporated Iodised, 1kg Pouch",
        tag: "Tata-Salt",
        des: " mental development of children",
        catagory: "spices&masalas",
        price: 23,
        inCart: 0,
    },
    {
        name: "Tata Salt Superlite, 1kg",
        tag: "Tata-Salt-Superlite",
        des: " LOW SODIUM SALT: New Tata Salt SuperLite has been specially formulated to provide 30% less sodium than refined iodized salt",
        catagory: "spices&masalas",
        price: 54,
        inCart: 0,
    },
    {
        name: "Malikaz' The Royale Taste Dried Rosemary Leaves Jar, 35 g | Versatile | 100% Natural | No Additives | Easy to Provide Seasoning to soups, casseroles, Salads, stews, etc |",
        tag: "Malikaz'-The-Royale-Taste-Dried",
        des: " Our spices & herbs follow a very unique journey. They are sourced directly from the farmers and then are washed, dried, dehydrated and then controlled for humidity and temperature before packaging",
        price: 69,
        catagory: "spices&masalas",
        inCart: 0,
    },
    {
        name: "24 Mantra Organic Flax Seeds/Alsi/Avise Ginjalu - 200gms, Pack of 1, Health Seeds, 100% Organic",
        tag: "24-Mantra-Organic-Flax-Seeds",
        des: " Beneficial to reduce risk cardio-vascular disease and type 2 diabetes",
        price: 60,
        catagory: "seed",
        inCart: 0,
    },
    {
        name: "catch Turmeric Powder, 500g, Natural",
        tag: "catch-Turmeric-Powder",
        des: " HIGH IN CURCUMIN: Catch Turmeric Powder has a distinct colour, flavour and is high in curcumin content.",
        price: 120,
        catagory: "spices&masalas",
        inCart: 0,
    },
    {
        name: "Catch Ginger Garlic Paste, 200 g",
        tag: "Catch-Ginger-Garlic-Paste",
        des: " READY TO USE: Catch Ginger Garlic Paste/ Adrak LahsunPaste is ready-to-use and is ideal to use in semi-dry and gravy-based preparations. Whether it is sambhar, matar paneer or malai kofta; turn your food into a mouth-watering delicacy in no time.",
        price: 37,
        catagory: "spices&masalas",
        inCart: 0,
    },
    {
        name: "Everest Masala Powder - Chicken, 100g Carton",
        tag: "Everest-Masala-Powder",
        des: " A perfect blend of pure spices",
        price: 72,
        catagory: "spices&masalas",
        inCart: 0,
    },
    {
        name: "Catch Chicken Masala, 100g",
        tag: "Catch-Chicken-Masala",
        des: " Catch Chicken Masala is an essential masala for Indian preparation of chicken. Adds aroma and distinctive flavour to the chicken dish.",
        price: 60,
        catagory: "spices&masalas",
        inCart: 0,
    },
    {
        name: "Sunrise Pure Chicken Curry Masala Spice Powder Pouch, 50 g",
        tag: "Sunrise-Pure-Chicken-Curry-Masala",
        price: 39,
        des: " For Sunrise Pure, quality is god. And god, they say, is in the details The very first quality check takes place at the time of procuring raw materials, the next when the materials enter our plants The raw materials then undergo cleaning, sorting, grading, low temperature grinding and state-of- the-art packaging, all of which are preceded and followed by stringent quality checks It is this no-compromise attitude towards quality that gives us the confidence to promise you the best and bring you the purest",
        catagory: "spices&masalas",
        inCart: 0,
    },
    {
        name: "Everest Masala, Garam, 100g Carton",
        tag: "Everest-Masala-Garam",
        des: " This all-purpose seasoning adds sweet flavor Rich aromatic blend of spices No cholestrol No trans fat variety: fennel item_form: powders",
        catagory: "spices&masalas",
        price: 79,
        inCart: 0,
    },
    {
        name: "Catch Compounded Hing, 100g",
        tag: "Catch-Compounded-Hing",
        des: " ingredients: asafoetidawheat flouredible gum Wholesome flavour of authentic spices Maximum Shelf Life 12 Months item_form: powders Original aroma material_features: vegetarian",
        price: 182,
        catagory: "spices&masalas",
        inCart: 0,
    },
    {
        name: "Dr Foot Cracked Heel Repair Oil for Soothing & Healing Cracked Heel | Make Heels Soft & Supple – 100ml",
        tag: "Dr-Foot-Cracked-Heel-Repair-Oil",
        des: " Our Foot Cracked Heel Oil for Cracked Heels, Tired Feet, Swollen Feet and Rough and Dry Feet. It can be used by both Men & Women.",
        price: 179,
        catagory: "beauty&care",
        inCart: 0,
    },
    {
        name: "The Moms Co. Natural Foot Cream With Argon oil, Vit E & Peppermint Essential Oil Relief for Swollen Ankles and Feet- 50 g",
        tag: "The-Moms-Co.-Natural-Foot-Cream",
        des: " This all natural cooling foot cream from our range of skin care is ideal for anyone looking for relief from cracked heels, swollen feet and tired feet and ankles",
        price: 174,
        catagory: "beauty&care",
        inCart: 0,
    },
    {
        name: "FURR Natural Hair Removal Cream -100gm | Removes Hair In 5 Minutes | Soothes Skin | Enriched With Vitamin E Turmeric, Honey, Jojoba Oil & Avocado | For Men and Women | Suitable For All Skin Types",
        tag: "FURR-Natural-Hair-Removal-Cream",
        des: " All skin Types: Hair Removal cream is suitable for all skin types, and does not cause any harm to the skin",
        price: 199,
        catagory: "beauty&care",
        inCart: 0,
    },
    {
        name: "Happilo 100% Natural Premium California Almonds 500g Pack Pouch | Premium Badam Giri | High in Fiber & Boost Immunity | Real Nuts | Gluten Free",
        tag: "Happilo-100%-Natural-California-Almonds",
        des: "Suitable for all age groups 100% Real nuts- good for an active life style Low glycemic Index High protein, dietary fiber, no gluten, NON-GMO, zero trans fat, zero cholesterol",
        price: 439,
        catagory: "food",
        inCart: 0,
    },
    {
        name: "Olive Oil",
        tag: "oli",
        des: " this is discription",
        price: 155,
        catagory: "nut",
        inCart: 0,
    },
    {
        name: "Tata Tea Premium | Desh Ki Chai |Unique Blend Crafted For Chai Lovers Across India | Black Tea | 1.5kg",
        tag: "Tata-Tea",
        des: " Unique Blend: Indulge in a unique blend crafted by Tea experts",
        price: 540,
        catagory: "tea",
        inCart: 0,
    },
    {
        name: "Nestle EVERYDAY Dairy Whitener, Milk Powder for Tea, 1Kg Pouch",
        tag: "Nestle-EVERYDAY-Dairy-Whitener-Milk",
        price: 515,
        des: " Nestle everyday is a tea enhancer that mixes in completely with your tea to lift its taste Ranked No. 1 by consumers in blind taste tests.",
        catagory: "tea",
        inCart: 0,
    },
    {
        name: "Tata Tea Gold | Assam teas with Gently Rolled Aromatic Long Leaves | Rich & Aromatic Chai | Black Tea | 1 kg",
        tag: "Tata-Tea-Gold",
        des: " For discerning tea Drinking consumers: Enjoy the superior balance of rich taste and irresistible aroma with Tata Tea Gold",
        catagory: "tea",
        price: 518,
        inCart: 0,
    },
    {
        name: "Maggi 2-Minute Noodles Masala, 70g (Pack of 12)",
        tag: "Maggi-Noodles-Masala",
        des: " Milk may contain, Soy may contain, Mustard may contain",
        catagory: "noodles",
        price: 160,
        inCart: 0,
    },
    {
        name: "Quaker Oats 2kg | Rolled Oats | 100% Natural Wholegrain | Nutritious Breakfast Cereals | Porridge | Easy to Cook",
        tag: "Quaker-Oats",
        des: " Vegetarian",
        price: 306,
        catagory: "oats",
        inCart: 0,
    },
    {
        name: "NESCAFÉ Classic Black Roast Instant Coffee, Rich & Dark - 100g Dawn Jar | 100% Pure Soluble Coffee Powder",
        tag: "NESCAFÉ-Classic",
        des: " Dark_roast",
        price: 340,
        catagory: "coffee",
        inCart: 0,
    },
    {
        name: "Lipton Honey Lemon Green Tea Bags 100 pcs, All Natural Flavour, Zero Calories - Improves Metabolism & Reduces Waist",
        tag: "Lipton-Honey-Lemon-Green-Tea-Bags",
        des: " Honey;green_tea;Lemon",
        price: 475,
        catagory: "tea",
        inCart: 0,
    },
    {
        name: "Real Fruit Power, Mixed Fruit, 1L (Pack of 2)",
        tag: "Real-Fruit-Power",
        des: " Mixed Fruit",
        price: 205,
        catagory: "Juices&fizzydrinks",
        inCart: 0,
    },
    {
        name: "Paper Boat Aamras, Mango Fruit Juice, No Added Preservatives and Colours (Pack of 6, 200ml each)",
        tag: "Paper-Boat-Aamras",
        des: " No Artificial Colors, No Preservatives",
        price: 171,
        catagory: "Juices&fizzydrinks",
        inCart: 0,
    },
    {
        name: "Tang Instant Drink Mix - Orange, 500g - Pack of 2 with 4 Popsicle moulds",
        tag: "Tang-Instant-Drink",
        des: " Powder,Vegetarian",
        price: 420,
        catagory: "Juices&fizzydrinks",
        inCart: 0,
    },
    {
        name: "Happilo Premium International Healthy Nutmix 200g | Mixed Dry Fruit & Healthy Snack | Nutritious| Snack Pack with high Protein & Calcium | Contains Kaju, Badam, Kismis, Munakka & more",
        tag: "Happilo-Premium-International-Healthy-Nutmix",
        price: 255,
        des: " High protein, high dietary fibre, no gluten, no gmo, zero trans fat, zero cholesterol, healthy nuts and dried fruits, good for an active lifestyle, low in fat, calories and sodium, ideal for weight watchers, high in proteins and anti oxidants, slows the ageing process and keeps diseases away, rich source of minerals, folic acid, calcium and iron, improves digestion, immunity, mental health, stop urinary tract infections",
        catagory: "dryfruits&snacks",
        inCart: 0,
    },
    {
        name: "Happilo Premium Roasted Pumpkin Seeds for Eating 200g | Lightly Salted for Healthy Diet | Immunity Booster and Fiber Rich Superfood | Crunchy Healthy Snack",
        tag: "Roasted-Pumpkin-Seeds",
        des: " Salted,Roasted,Tree Nuts, Gluten Free ",
        catagory: "dryfruits&snacks",
        price: 167,
        inCart: 0,
    },
    {
        name: "True Elements 7 in 1 Super Seeds Mix 250g - Seeds for Eating | Mix Seeds | Diet Snacks | Roasted Seeds",
        tag: "7-in-1-Super-Seeds-Mix",
        des: " Roasted Seeds",
        price: 269,
        catagory: "dryfruits&snacks",
        inCart: 0,
    },
    {
        name: "Happilo Premium Dried Super Mix Berries 200gm | Tasty & Healthy Berries | Rich in Antioxidant | Contains Dried Strawberries, Cranberries, Cherry & Raisins Mix | Real Dried Berries",
        tag: "Mix-Berries",
        des: " this is discription",
        price: 251,
        catagory: "dryfruits&snacks",
        inCart: 0,
    },
    {
        name: "Nutty Gritties Mix Berries Dried Fruits Berry 200g - Dried Cranberries, Blueberries, Strawberries, Black Currants - Healthy Snack for Kids and Adults",
        tag: "Dried-Fruits-Berry",
        des: " 	Alcohol Free",
        price: 299,
        catagory: "dryfruits&snacks",
        inCart: 0,
    },
    {
        name: "Nutty Gritties Super Seeds Mix - Roasted 200g- Flax, Chia, Sesame, Sunflower, Watermelon, Pumpkin Seeds, Mixed Seeds for Eating",
        tag: "Nutty-Gritties-Super-Seeds",
        des: " Roasted",
        price: 175,
        catagory: "dryfruits&snacks",
        inCart: 0,
    }, ,
    {
        name: "Nutraj Signature Premium Daily Needs Fresh and Healthy Mixed Dry Fruits Combo of Almonds, Cashews, Raisins, Pistachios & Walnut Halves Kernels 1 Kg Pack (200g Each x5)",
        tag: "Daily-Needs-Fresh",
        des: " Vegan ",
        price: 1316,
        catagory: "dryfruits&snacks",
        inCart: 0,
    },
    {
        name: "Parle Hide and Seek Chocolate Chip Cookies, 200g",
        tag: "Parle-Hide-and-Seek",
        des: " 	Suitable for vegeterians",
        price: 60,
        catagory: "biscuit",
        inCart: 0,
    },
    {
        name: "UNIBIC FOODS Cashew Badam Cookies, 500g",
        tag: "UNIBIC-FOODS-Cashew",
        price: 145,
        des: " Vegetarian",
        catagory: "biscuite",
        inCart: 0,
    },
    {
        name: "Sunfeast Dark Fantasy Choco Fills, 300g, Original Filled Cookies with Choco Crème",
        tag: "Sunfeast-Dark-Fantasy-Choco",
        des: " 	Chocolate",
        catagory: "biscuite",
        price: 160,
        inCart: 0,
    },
    {
        name: "Mom's Magic Rich Cashew Almond Cookies | Roasted Cashew Almond | Rich Butter biscuits | Mom's favourite baked cookies 200g",
        tag: "Mom's-Magic-Rich",
        des: " Suitable for vegetarians",
        catagory: "biscuits",
        price: 39,
        inCart: 0,
    },
    {
        name: "UNIBIC Fruit & Nut Cookies, 500 g",
        tag: "UNIBIC-Fruit-&-NutCookies",
        des: " Vegetarian",
        price: 160,
        catagory: "biscuits",
        inCart: 0,
    },
    {
        name: "Parle Krackjack Biscuits, 200g",
        tag: "Parle-Krackjack-Biscuits",
        des: " Suitable for Vegetarians",
        price: 35,
        catagory: "biscuits",
        inCart: 0,
    },
    {
        name: "Cadbury Chocobakes Choc Filled Cookies, 150 g",
        tag: "Cadbury-Chocobakes-Choc-Filled-Cookies",
        des: " Suitable for vegetarians",
        price: 60,
        catagory: "biscuits",
        inCart: 0,
    },
    {
        name: "Lay's American Style Potato Chips - Cream & Onion, 52g, Pink",
        tag: "Lay's-American-Style-Potato-Chips",
        des: " Zero Trans Fat, Vegetarian",
        price: 20,
        catagory: "chips",
        inCart: 0,
    },
    {
        name: "Bingo! Mad Angles Tomato Madness, 66 g Pack, Tangy & Crunchy Chips Perfect for Snacking",
        tag: "Bingo!-Mad-Angles-Tomato-Madness",
        des: " 5.6 x 13 x 17.5 Centimeters",
        price: 20,
        catagory: "chips",
        inCart: 0,
    },
    {
        name: "Lays Spanish Tomato Tango 115g",
        tag: "Lays-Spanish-Tomato-Tango",
        des: " Vegetarian",
        price: 50,
        catagory: "chips",
        inCart: 0,
    },
    {
        name: "Haldirams Fatafat Bhel, 150g",
        tag: "Haldirams-Fatafat-Bhel",
        price: 30,
        des: " Sour",
        catagory: "namkeen",
        inCart: 0,
    },
    {
        name: "Haldirams Bhujia, 400g",
        tag: "Haldirams-Bhujia",
        des: " Savory",
        catagory: "namkeen",
        price: 104,
        inCart: 0,
    },
    {
        name: "Bikano Navratan Mixture, 1kg",
        tag: "Bikano-Navratan-Mixture",
        des: " 	Spicy, Suitable for vegetarian",
        price: 272,
        catagory: "namkeen",
        inCart: 0,
    },
    {
        name: "Parle Monaco Cheeselings, Classic, 150g Jar",
        tag: "Parle-Monaco-Cheeselings",
        des: " Suitable for vegeterians",
        price: 58,
        catagory: "namkeen",
        inCart: 0,
    },
    {
        name: "Haldirams Namkeen - Cornflake, Mixture 200g",
        tag: "	 Haldirams-Namkeen-Cornflake",
        des: " Cornflake",
        price: 70,
        catagory: "namkeen",
        inCart: 0,
    },
    {
        name: "BIKANO Aloo Bhujia, 500gm(400g+100g)",
        tag: "BIKANO-Aloo-Bhujia",
        des: " Spicy",
        price: 81,
        catagory: "namkeen",
        inCart: 0,
    },
    {
        name: "Haldiram's Nagpur Tasty Nuts, 200g",
        tag: "Haldiram's-Nagpur-Tasty-Nuts",
        des: "Spicy",
        price: 101,
        catagory: "namkeen",
        inCart: 0,
    },
    {
        name: "Bikano Shahi Mix, 1kg",
        tag: "Bikano-Shahi-Mix",
        des: " 	Spicy, Sweet",
        price: 230,
        catagory: "namkeen",
        inCart: 0,
    },
    {
        name: "Act II Instant Popcorn Party Pack, Butter Delite, 3x150g (Buy 2 Get 1 Free)",
        tag: "Instant-Popcorn-Party-Pack",
        des: " Goodness of corn Hot and fresh popcorn Zero gram trans fat Instant popcorn For the party plan",
        price: 123,
        catagory: "Popcorn",
        inCart: 0,
    },
    {
        name: "Act II IPC Golden Sizzle Popcorn, 40g",
        tag: "IPC-Golden-Sizzle-Popcorn",
        price: 10,
        des: " Fat Free",
        catagory: "Popcorn",
        inCart: 0,
    },
    {
        name: "Desire Popcorn Kernel Seeds 1 Kg | Big Size Gourmet Pop Corn Kernels Imported | High Expansion, A Grade Makkai Popcorn",
        tag: "Desire-Popcorn-Kernel-Seeds",
        des: " Vegetarian",
        catagory: "popcorn",
        price: 285,
        inCart: 0,
    },
    {
        name: "Sambha Khakhra 4 Flavor Combo Methi, Masala, Jeera & Plain | Gujrati Indian Snacks | Healthy | 100% Natural Ingredient | Diet Friendly (800g, Pack of 40, 4*200g)",
        tag: "Sambha-Khakhra-4-Flavor-Combo-Methi",
        des: " No Preservatives",
        catagory: "khakhra",
        price: 273,
        inCart: 0,
    },
    {
        name: "Snackible Crispy Cheese Dosa Khakhra (Pack of 3) 3x100gm| Healthy | Made with Ragi | High in Protein | Gluten Free | Zero Preservatives",
        tag: "Snackible-Crispy",
        des: " CRISPY DOSA KHAKHRA: We at Snackible have combined two delicious delicacies of India into one. Dosa from South India and Khakhra from North India together form a healthy and crispy snack with a delicious flavor profile in every bite. The crunchy texture of this dosa khakhra is going to leave you wanting more.",
        price: 270,
        catagory: "khakhra",
        inCart: 0,
    },
    {
        name: "Paper Boat Aam Papad Family Pack, Fruit Bar, No Added Preservatives and Colours, (Pack of 3, 90g Each)",
        tag: "Paper-Boat-Aam-Papad",
        des: " Aam Papad, is a plant-based candy , are unequivocally every Indian kid’s favourite childhood snack that we never thought twice before squandering our pocket money ",
        price: 185,
        catagory: "papad",
        inCart: 0,
    },
    {
        name: "Mother's Recipe Rice Papad - Ajwain, 75g",
        tag: "Mother's-Recipe-Rice-Papad",
        des: " Vegetarian",
        price: 24,
        catagory: "papad",
        inCart: 0,
    },
    {
        name: "Ganesh Premium Bikaneri Special Moong Papad-400gms (9 Inch)",
        tag: "Ganesh-Premium",
        des: " Suitable for vegetarians",
        price: 165,
        catagory: "papad",
        inCart: 0,
    },
    {
        name: "Paper Boat Chikki Jar, Peanut Bar, No Added Preservatives and Colours | Gajak | Sweets | Made with Jaggery | Gazak (50 pieces, 16g each)",
        tag: "Paper-Boat-Chikki-Jar",
        des: " No artificial flavour, Fairtrade, Gluten Free",
        price: 234,
        catagory: "chikki",
        inCart: 0,
    },
    {
        name: "Postcard Kovilpatti Peanut Chikki 600G | No Sugar, no preservatives | Pure Jaggery mittai | Crunchy Sweet Peanut Bar Made with Jaggery | Traditional Indian Sweets | Pack of 3 x 200G",
        tag: "Postcard-Kovilpatti-Peanut-Chikki",
        des: " Crunchy & Tasty Peanut Chikki Made with Jaggery.....No Sugar Added Authentic Snack From Tamilnadu Hygenically Made And Packed",
        price: 249,
        catagory: "chikki",
        inCart: 0,
    },
    {
        name: "SIRIMIRI Classic Peanut Chikki - Made With Pure Jaggery 800G (32N x 25G)",
        tag: "SIRIMIRI-Classic-Peanut-Chikki",
        price: 399,
        des: " Our motherland is known for its traditions. Traditions are deep rooted in simplicity and practicality. Chikkies are simple products, made with what is naturally and locally available. We present you the best Chikkies made with pure Jaggery. Our Chikkies will impress you with the taste and help you with the nature given nutrition.",
        catagory: "chikki",
        inCart: 0,
    },
    {
        name: "Yogabar Breakfast Protein Variety (Almond Coconut, Apricot & Fig, Blueberry, Apple Cinnamon Bars - 300gm, 6 x 50 g (Box of 6 Bars)",
        tag: "Yogabar-Breakfast-Protein-Variety",
        des: " HEALTHY BREAKFAST PROTEIN BAR: With quinoa, oats, millet, almonds, peanuts, flax and chia seeds",
        catagory: "snackbars",
        price: 275,
        inCart: 0,
    },
    {
        name: "Yogabar Chocolate Chunk Multigrain-Energy Bars - Healthy Diet Snacks with Almonds, Oats and Millets, Gluten Free and High Protein Crunchy Nut Bar, Packed with Chia and Sunflower Seeds (38G*10 Bars)",
        tag: "Yogabar-Chocolate-Chunk",
        des: " Store in a cool dry place;10 - 15% Seeds. We use: Flax,Chia,Sunflower,Sesame,Watermelon,Melon,Pumpkin;Our first ingredient is always a nutrient dense ingredient like whole grains,nuts or seeds;No Corn Syrup or Artificial Sweeteners and No Hydrogenated Oils . ",
        price: 369,
        catagory: "snackbars",
        inCart: 0,
    },
    {
        name: "NESTLE GOLD Crunchy Nutty Granola, Breakfast Cereal - 475g",
        tag: "NESTLE-GOLD-Crunchy-Nutty-Granola",
        des: " GOLD Crunchy Nutty Granola consists of rolled oats, wheat, almonds, raisins and honey for the perfect crunch to your breakfast",
        price: 219,
        catagory: "snacksbars",
        inCart: 0,
    },
    {
        name: "Monsoon Harvest Crunchy Millet Granola Bars - Dark Chocolate & Espresso - Pack of 6, Healthy Breakfast Snacks, Gluten Free Energy Bars, High Fiber (40 Gm Each), with Rolled Oats",
        tag: "Monsoon-Harvest-Crunchy-Millet-Granola-Bars",
        des: " This is a Vegetarian product. 100% NATURAL & GLUTEN-FREE: Made of pure wholegrain rolled oats and locally grown millets HIGH-FIBRE & RICH IN WHOLE GRAINS: Energy-packed bars, with 4.2 g fiber and 20 g of Whole Grains",
        price: 207,
        catagory: "snacksbar",
        inCart: 0,
    },
    {
        name: "Monsoon Harvest Nuts & Seeds Energy Bars - Dark Chocolate & Sea Salt - 180 g (Pack of 6 x 30g), Almonds, cashews, pumpkin seeds & Dry Fruit, Healthy Protein Snack Bars, All Natural, Plant Based",
        tag: "Monsoon-Harvest-Nuts-&-Seeds-Energy-Bar",
        des: " 100% NATURAL & GLUTEN-FREE: Get a healthy start every morning with Nuts and Seeds Bars from Monsoon Harvest. These nutritious gluten-free bars contain 60% nuts & seeds, such as almonds, cashews, green pumpkin and flax seeds.",
        price: 389,
        catagory: "snacksbars",
        inCart: 0,
    }, ,
    {
        name: "Naturo (Mango & Orange, Fruit Bites 300g)",
        tag: "Mango-&-Orange-Fruit-Bites",
        des: " Each bar has all benefits of fruits. Each fruit bar is made from over 70% real Fruit Pulp! Great for picnics, lunchboxes or gifting.This delicious fruit bar is a perfect snack for the whole family.",
        price: 200,
        catagory: "snacksbars",
        inCart: 0,
    },
    {
        name: "Unibic Snack Bar Almond & Oats Pack of 12, 360g",
        tag: "Unibic-Snack-Bar-Almond-&-Oats",
        des: " Ingredient Type: Vegetarian;Beta glucans from oats boosts heart health;Flavour: Almond",
        price: 216,
        catagory: "snacksbars",
        inCart: 0,
    },
    {
        name: "Nature Valley Variety Pack Cereal Bars, 210g (2xCanadian Maple Syrup+1xOats & Dark Chocolate+2xOats & Honey Bars)",
        tag: "Nature-Valley-Variety-Pack-Cereal-Bars",
        price: 465,
        des: " 2 x Canadian Maple Syrup+1 x Oats & Dark Chocolate+2 x Oats & Honey Bars Imported",
        catagory: "snacksbars",
        inCart: 0,
    },
    {
        name: "NUTS ABOUT YOU Raisin Round Pouch, 500 g",
        tag: "NUTS-ABOUT-YOU-Raisin",
        des: " Hygienically packed in a facility meeting international food safety standards",
        catagory: "Dried Fruits",
        price: 139,
        inCart: 0,
    },
    {
        name: "Ariel Top Load Liquid detergent  (500 ml Extra in Pack)  (2 L)",
        tag: "Ariel-Top-Load-Liquid-detergent",
        des: " Removing stains from clothes is convenient, thanks to the reliable Ariel Matic Liquid detergent. It quickly dissolves in water and removes stains without leaving behind any patchy residue. Also, this liquid detergent does its job without affecting the colour of the fabric while washing.",
        catagory: "detergent",
        price: 392,
        inCart: 0,
    },
    {
        name: "Tide Double Power Jasmine and Rose detergent Powder 4 kg  (1KG Tide with Extra Power Free)",
        tag: "Tide-Double-Power",
        des: " New Tide Plus Double Power detergent powder has Stain Magnets, which can remove the toughest of stains to give you STAINLESS WHITES. Tide Plus' improved formulation and enzyme system has been specially designed to beat tough kitchen stains and give you outstanding whiteness.",
        price: 420,
        catagory: "detergent",
        inCart: 0,
    },
    {
        name: "Surf excel Easy Wash detergent Powder 1.5 kg",
        tag: "Surf-excel-Easy-Wash",
        des: " Hand Wash detergent",
        price: 191,
        catagory: "detergent",
        inCart: 0,
    },
    {
        name: "Surf excel Matic Top Load Liquid detergent  (0.5 L)",
        tag: "Surf-excel-Liquid-detergent",
        des: " Fragrance-Free",
        price: 96,
        catagory: "detergent",
        inCart: 0,
    },
    {
        name: "Surf excel detergent Bar  (800 g, Pack of 4)",
        tag: "Surf-excel-detergent-Bar",
        des: " Fragrance-Free",
        price: 108,
        catagory: "detergent",
        inCart: 0,
    },
    {
        name: "Vanish All in One Liquid detergent Booster - 800 ml Stain Remover",
        tag: "Vanish-All-in-One-Liquid",
        des: " You can remove stubborn stains effectively from your clothes with just one wash by using the Vanish All-in-one detergent Boosting Add-on Liquid and Stain Remover. It is infused with active oxygen that functions as a catalyst to the reaction between surfactants and dirt particles, giving you clean, stain-free clothes that will dazzle you with their freshness.",
        price: 148,
        catagory: "detergent",
        inCart: 0,
    },
    {
        name: "Rin Bright Like New detergent Powder 4 kg",
        tag: "Rin-Bright-Like-New-detergent-Powder",
        des: " Bright Like New",
        price: 325,
        catagory: "detergent",
        inCart: 0,
    },
    {
        name: "Comfort After Wash Morning Fresh Fabric Conditioner  (860 ml)",
        tag: "Comfort-After-Wash",
        price: 199,
        des: " Morning Fresh",
        catagory: "detergent",
        inCart: 0,
    },
    {
        name: "Surf excel Matic Front Load Detergent Powder 2 kg",
        tag: "Surf-excel-Matic-Front-Load-Detergent-Powder",
        des: " Matic Front Load",
        catagory: "detergent",
        price: 385,
        inCart: 0,
    },
    {
        name: "Comfort After Wash Lily Fresh Fabric Conditioner  (2 L)",
        tag: "after-wash-lily-fresh",
        des: " Lily Fresh",
        price: 421,
        catagory: "detergent",
        inCart: 0,
    },
    {
        name: "Giffy Concentrated Dish Cleaning Gel  (Plain, 2 x 0.5 L)",
        tag: "Dish-Cleaning-Gel",
        des: " Concentrated",
        price: 147,
        catagory: "householdcare",
        inCart: 0,
    },
    {
        name: "Vim Dishwash Anti Bac Liquid Dish Cleaning Gel  (Neem, 2 L)",
        tag: "Vim-Dish-Cleaning-Gel",
        des: " Dishwash Anti Bac Liquid",
        price: 363,
        catagory: "householdcare",
        inCart: 0,
    },
    {
        name: "Vim Dishwash Bar  (300 g)",
        tag: "Vim-Dishwash-Bar",
        des: " Lemon",
        price: 27,
        catagory: "householdcare",
        inCart: 0,
    },
    {
        name: "Exo Touch & Shine Round Dishwash Bar  (Exo Super Scrubber Worth Rs.15 Free)  (700 g)",
        tag: "Exo-Dishwash",
        des: "Touch & Shine Round",
        price: 63,
        catagory: "householdcare",
        inCart: 0,
    },
    {
        name: "Pril Perfect Dish Cleaning Gel  (Lime, 0.75 L)",
        tag: "Pril-Perfect-Dish-Cleaning-Gel",
        des: " Lime",
        price: 149,
        catagory: "householdcare",
        inCart: 0,
    },
    {
        name: "Exo Dishwash Bar",
        tag: "Exo-Dishwash-Bar",
        des: " 300 g",
        price: 30,
        catagory: "householdcare",
        inCart: 0,
    },
    {
        name: "Pitambari Shining Powder Dishwashing Detergent  (200 g)",
        tag: "Pitambari-Shining-Powder-Dishwashing-Detergent",
        price: 49,
        des: " Manual Wash",
        catagory: "householdcare",
        inCart: 0,
    },
    {
        name: "Pril Dishwash Bar",
        tag: "Pril-Dishwash-Bar",
        des: " 1.2 kg",
        catagory: "householdcare",
        price: 99,
        inCart: 0,
    },
    {
        name: "Scotch-Brite Super Strong Scrub Pad",
        tag: "Scotch-Brite-Scrub-Pad",
        des: " The Scotch Brite scrub pad can be used to clean your pressure cookers, tawas, kadhais, and more so that stains, dirt, oil, and more can be properly cleaned.",
        catagory: "householdcare",
        price: 36,
        inCart: 0,
    },
    {
        name: "Domex Fresh Guard Ocean Liquid Toilet Cleaner",
        tag: "Domex-Toilet-Cleaner",
        des: " Liquid",
        price: 273,
        catagory: "householdcare",
        inCart: 0,
    },
    {
        name: "Harpic Power Plus Original Liquid Toilet Cleaner(2 x 1 L)",
        tag: "Harpic-Toilet-Cleaner",
        des: " You can keep the germs and stains at bay and maintain a clean, hygienic toilet with the powerful Harpic Power Plus toilet cleaner liquid",
        price: 296,
        catagory: "householdcare",
        inCart: 0,
    },
    {
        name: "Harpic Disinfectant Bathroom Cleaner Liquid Lemon  (1 L)",
        tag: "Harpic-Bathroom-Cleaner-Liquid",
        des: " The Harpic Disinfectant bathroom cleaner liquid helps you remove greasy oil, dirt, and germs from your bathroom, ensuring it stays clean and hygienic.",
        price: 149,
        catagory: "householdcare",
        inCart: 0,
    },
    {
        name: "Lizol Disinfectant Surface Cleaner Citrus  (975 ml)",
        tag: "Lizol-Surface-Cleaner",
        des: " Keep your home fresh and clean with the Lizol Disinfectant Surface Cleaner that can kill all potential germs protecting you from hazardous diseases.",
        price: 164,
        catagory: "householdcare",
        inCart: 0,
    },
    {
        name: "Harpic Power Plus Orange Liquid Toilet Cleaner  (1 L)",
        tag: "Harpic-Toilet-Cleaner1L",
        des: " Maintaining a hygienic toilet is crucial to maintain a healthy lifestyle, and the Harpic Power Plus Orange Liquid Toilet Cleaner ensures that your toilets at home are clean and germ-free.",
        price: 158,
        catagory: "householdcare",
        inCart: 0,
    },
    {
        name: "Colin Glass and Surface Cleaner Liquid Spray, Regular  (500 ml)",
        tag: "Colin-Glass-Cleaner",
        des: " The Colin Glass and Multisurface Cleaner works effectively on smears and smudges to clean, brighten, and shine surfaces.",
        price: 82,
        catagory: "householdcare",
        inCart: 0,
    },
    {
        name: "Pears Pure & Gentle Bathing Bar  (3 x 125 g)",
        tag: "Pears-Bath-Bar",
        price: 161,
        des: " Let the Pears Pure & Gentle Soap Bar take care of your skin, as this soap is milder than a baby’s soap. It is enriched with pure glycerin, skin conditioning agents and mild cleansers, to cleanse your skin in a gentle way.",
        catagory: "personal-care",
        inCart: 0,
    },
    {
        name: "Lakmé Perfect Radiance Skin Lightening Face Wash  (51 g)",
        tag: "Lakmé-Face-Wash",
        des: " Make this Lakme Perfect Radiance Skin Lightening Face Wash a part of your cleansing ritual every day. This gentle formula takes on multiple skin problems while also nourishing your face.",
        catagory: "personal-care",
        price: 134,
        inCart: 0,
    },
    {
        name: "BOROPLUS Antiseptic + Moisturising Soap - Neem, Tulsi & Aloe Vera  (6 x 125 g)",
        tag: "BOROPLUS-Soap",
        des: " BoroPlus Antiseptic and Moisturising Bathing Soap consist of Neem which has anti-viral, anti-bacterial, and anti-oxidant properties which kill 99.9% of germs and viruses",
        price: 154,
        catagory: "personal-care",
        inCart: 0,
    },
    {
        name: "Dettol Original Liquid Hand Wash Refill Pouch  (750 ml)",
        tag: "Dettol-Original-Liquid-Hand-Wash",
        des: " Use the Dettol Refill Original pack and keep your hands germ-free and refreshed for a long time. It is recommended by the Indian Medical Association to ensure a healthy and hygienic lifestyle.",
        price: 87,
        catagory: "personal-care",
        inCart: 0,
    },
    {
        name: "Margo Original Neem Soap  (Combo Pack 6 + 2 Free, 125 g each)  (6 x 125 g)",
        tag: "Margo-Neem-Soap",
        des: " Original Neem Soap,Men & Women",
        price: 204,
        catagory: "personal-care",
        inCart: 0,
    },
    {
        name: "CINTHOL Original Soap  (8 x 100 g)",
        tag: "CINTHOL-Soap",
        des: " High TFM (Grade 1 soap) keeps your skin healthy and glowing. Recommended by doctors to reduce risk of skin problems by 95%. Reduces risk of skin problems like acne, blemishes and rashes. Suitable for all skin types and all age groups. Ideal for Men & Women",
        price: 247,
        catagory: "personal-care",
        inCart: 0,
    },
    {
        name: "Dettol Cool Germ Protection Bathing Soap  (Combo Pack 3 + 1 Free, 100 g each)  (3 x 75 g)",
        tag: "Dettol-Cool-Soap",
        des: " Germ Protection: Dettol soap protects from 99.9% germs including virus and bacteria. Recommended by Indian Medical Association (IMA). Intense Cooling: Contains 2X menthol for intense cooling effect. Bathing: Contains 76% TFM for rich and creamy lather. Natural cleansers: Contains more than 85% naturally derived ingredients and plant derived cleansers. New Pack: Now with 2x menthol.",
        price: 126,
        catagory: "personal-care",
        inCart: 0,
    },
    {
        name: "santoor Sandal & Turmeric Soap  (8 x 125 g)",
        tag: "santoor-Soap",
        des: " This pack of Santoor Sandal and Turmeric Soap brings together two ingredients which have been an essential part of the Indian skincare regimen for centuries now. Because of the antiseptic properties of sandalwood and turmeric, this soap not only cleans your skin, but also helps with getting rid of tan, curing itches, and detoxifying the skin.",
        price: 290,
        catagory: "personal-care",
        inCart: 0,
    },
    {
        name: "MEDIMIX Ayurvedic Classic 18 Herbs Soap  (6 x 125 g)",
        tag: "MEDIMIX-Ayurvedic-Soap",
        des: " Ayurvedic Classic 18 Herbs Soap",
        price: 175,
        catagory: "personal-care",
        inCart: 0,
    },
    {
        name: "FAIR AND HANDSOME Instant Radiance Face Wash  (100 g)",
        tag: "DSOME-Face-Wash",
        des: " Oil Control, Skin Brightening",
        price: 101,
        catagory: "personal-care",
        inCart: 0,
    },
    {
        name: "Godrej No.1 Sandal Turmeric Bathing Soap  (9 x 150 g)",
        tag: "Godrej No.1-Soap",
        des: " Sandal Turmeric Bathing Soap",
        price: 291,
        catagory: "personal-care",
        inCart: 0,
    },
];